### ISSUE TITLE
Feature Request: Ephemeral Disk Encryption

### ISSUE THREAD

**Issue by scult** [cloudfoundry-incubator/bosh-alicloud-cpi-release#33]
For increased security it would be helpful if we could encrypt our ephemeral disks.

Currently the CPI doesn't support encrypting ephemeral disks. Please add a feature to configure this via the cloud config.

I would propose using the same format as the AWS-CPI  e.g.:

```
vm_types:
- cloud_properties:
    ephemeral_disk:
      *encrypted: true*
      size: "51_200"
    instance_type: ecs.sn2.medium
  name: medium
```
