### ISSUE TITLE
Attaching Security Groups via VM Extension

### ISSUE THREAD

**Issue by scult** [cloudfoundry-incubator/bosh-alicloud-cpi-release#38]
Hi Guimin,

attaching security groups to VMs via VM extensions doesn't seem to work anymore. Could this have something to do with the new feature to disable inner access? I am fairly sure that it was working during my previous tests.

Can you please take a look?

CPI Version: 18

Example from my cloud config:

```
vm_extensions:
- cloud_properties:
    security_groups: [sg-uf6i0wd4ev0nm3a9r6bb]
  name: consul-server
```

**Comment by xiaozhu36** [comment]
Hi @scult You should use "security_group_ids" not "security_groups", and you can refer to: https://github.com/cloudfoundry/cf-deployment/blob/master/iaas-support/alicloud/cloud-config.yml#L79

**Comment by scult** [comment]
Thanks for the quick reply @xiaozhu36. I've changed "security_groups" to "security_group_ids", but the behavior is still the same, only the security group as defined in the networks block is attached to the VM but not the security group defined as a VM extension.

Updated cloud config:
```
vm_extensions:
- cloud_properties:
    security_group_ids: [sg-uf6i0wd4ev0nm3a9r6bb]
  name: consul-server
```
