### ISSUE TITLE
Ephemeral disks are not deleted with the VM by default

### ISSUE THREAD

**Issue by firasnajjar** [cloudfoundry-incubator/bosh-alicloud-cpi-release#45]
According to the documentation [here](https://github.com/cloudfoundry-incubator/bosh-alicloud-cpi-release/blob/master/docs/bosh/alicloud-cpi.md#-resource-pools--vm-types) the default behavior of the CPI is to delete the ephemeral disk when the VM is deleted. This can be viewed under: ephemeral_disk -> delete_with_instance default: true. 

This is not the case, if you have a VM type defined in the cloud config like this: 

```
- name: vm_16cpu_30gb
  cloud_properties:
    instance_type: some_vm_type
    ephemeral_disk:
      size: "10_240"
```

The disk will NOT be deleted when the VM is deleted and you'll end up with a lot of unattached disks with time. 

If you explicitly define delete_with_instance to be true:
```
- name: vm_16cpu_30gb
  cloud_properties:
    instance_type: some_vm_type
    ephemeral_disk:
      size: "10_240"
      delete_with_instance: true
```

The ephemeral disk will be deleted with the VM. Therefore, the bug is only with the default value.
